/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function getInstanceVersion(): number[]
export interface Device {
  name: string
  major: number
  minor: number
  patch: number
}
export function getPhysicalVersions(): Array<Device>
